### ISSUE TITLE
Document Filesystem errors

### ISSUE THREAD

**Issue by beruic** [ionic-team/capacitor-site#264] opened 2021-04-16 13:38 UTC
There is no documentation of errors on rejection of file operations in the Filesystem plugin.

This goes for both https://capacitorjs.com/docs/apis/filesystem or https://capacitorjs.com/docs/v3/apis/filesystem

**Comment by jcesarmobile** [comment] 2022-08-25 13:25
closing as duplicate of https://github.com/ionic-team/capacitor-plugins/issues/351
docs are generated from the plugins, so should be fixed there

**Closed by jcesarmobile** 2022-08-25 13:25 UTC
