### ISSUE TITLE
Borken link in Using Capacitor with Ionic 

### ISSUE THREAD

**Issue by JumBay** [ionic-team/capacitor-site#115] opened 2020-09-06 11:49 UTC
In "Using Capacitor with Ionic" page https://capacitorjs.com/docs/getting-started/with-ionic, the latest link in the page: 
> Want to start using Capacitor in an Ionic app immediately? Check out this guide. 

links to https://capacitorjs.com/docs/guides/ionic-framework-app --> "Page not found"

**Comment by jcesarmobile** [comment] 2020-09-08 11:23
it's a duplicate of https://github.com/ionic-team/capacitor-site/issues/94

**Closed by jcesarmobile** 2020-09-08 11:23 UTC
