### ISSUE TITLE
[Docs] Deeplinked pages do not get highlighted in navigation

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor-site#17] opened 2019-06-14 16:05 UTC
When you open a link like https://capacitor.ionicframework.com/docs/basics/opening-native-projects the page is opened with the page highlighted in the navigation, but then the page "redisplays" and when that happened the page does not get highlighted in the navigation on the left. Only after navigating to a new page you get the highlight for the active page again.

(FF67 on Win10)

**Comment by jcesarmobile** [comment] 2021-05-19 17:21
I can't reproduce anymore, so should have been fixed on latest site improvements

**Closed by jcesarmobile** 2021-05-19 17:21 UTC
Labels: content
