### ISSUE TITLE
ios pod install not working

### ISSUE THREAD

**Issue by jordanrzymski** [ionic-team/capacitor-site#267] opened 2021-04-27 07:59 UTC
hello

I switch for cordova to capacitor for an ios build, but when I come to add the ios platform . I get this this part

  Found 5 Cordova plugins for ios
    cordova-plugin-advanced-http (3.0.1)
    cordova-plugin-file (6.0.2)
    cordova-plugin-network-information (2.0.2)
    cordova-plugin-purchase (10.5.3)
    cordova-sqlite-storage (5.1.0)
⠋ Updating iOS native dependencies with "pod install" (may take several minutes)

and it doesn't finish or timeout etc.

Can you suggest what I can do to fix this? I am on a 2019 mac and my pods are up to date.

Please help - my android platform works fine and I have a build.

I am pulling my hair out.

Jordan

**Comment by thomasvidas** [comment] 2021-04-27 20:24
Hello 👋  this seems to be a support request and this is the repo for the Capacitor documentation. If you need some help, you can check out our Capacitor forum here: https://forum.ionicframework.com/c/capacitor/26

I'll close this for now but if you think this is a bug feel free to open a ticket in on the main Capacitor repo with a reproducible example: https://github.com/ionic-team/capacitor

**Closed by thomasvidas** 2021-04-27 20:24 UTC
